<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <Configurations>Debug;Release;ci</Configurations>
	
  </PropertyGroup>

  <ItemGroup>
    <None Remove="appsettings.Development.json" />
    <None Remove="appsettings.Development.json.template" />
    <None Remove="appsettings.json" />
    <None Remove="appsettings.Production.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.Development.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="appsettings.Development.json.template" />
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="appsettings.Production.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
	
  <ItemGroup>
	  <PackageReference Include="AutoFixture" />
	  <PackageReference Include="coverlet.msbuild" />
	  <!--<PackageReference Include="coverlet.collector" /> try not to use both if dont have to-->
	  <PackageReference Include="Deque.AxeCore.Playwright" />
	  <PackageReference Include="FluentAssertions" />
	  <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
	  <PackageReference Include="Microsoft.NET.Test.Sdk" />
	  <PackageReference Include="Microsoft.Playwright" />
	  <PackageReference Include="Microsoft.Playwright.MSTest" />
	  <PackageReference Include="Microsoft.Playwright.Xunit" />
	  <PackageReference Include="Verify.Playwright" />
	  <PackageReference Include="xunit" />
	  <PackageReference Include="xunit.runner.visualstudio" />
	  <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
	  
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TELBlazor.Components.ShowCase.E2ETests.WasmServerHost\TELBlazor.Components.ShowCase.E2ETests.WasmServerHost\TELBlazor.Components.ShowCase.E2ETests.WasmServerHost.csproj" />
  </ItemGroup>

</Project>
