version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    target-branch: "Automatic_version_update_dependabot"  
    rebase-strategy: "auto"
    
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    target-branch: "Automatic_version_update_dependabot"
    rebase-strategy: "auto"