<?xml version="1.0" encoding="utf-8"?>
<Project>
  <Import Project="PackageSettings.props" />
  <Import Project="PackageSettings.props.local" Condition="Exists('PackageSettings.props.local')"/>
	<Target Name="PrintMSBuildThisFileDirectory" BeforeTargets="Test">
		<Message Importance="High" Text="qqqq" />
		<Message Importance="High" Text="MSBuildThisFileDirectory = '$(MSBuildThisFileDirectory)'" />
		<Message Importance="High" Text="MSBuildProjectDirectory = '$(MSBuildProjectDirectory)'" />
	</Target>
	<PropertyGroup>
		<!-- coverlet.msbuild, specifically msbuild props  -->
		<CollectCoverage>true</CollectCoverage>
		<CoverletOutputFormat>cobertura</CoverletOutputFormat>
		<Threshold>50</Threshold>
		<ThresholdType>line</ThresholdType>
		<ThresholdStat>total</ThresholdStat>
		<ThresholdBranch>50</ThresholdBranch>
		<ThresholdMethod>50</ThresholdMethod>
		<!-- Additional properties carried over from runsettings -->
		<Include>[TELBlazor.Components]*</Include>
		<ExcludeByAttribute>ExcludeFromCodeCoverage</ExcludeByAttribute>
		<ExcludeByFile>**/Program.cs,**/Components/TestComponents/*.*</ExcludeByFile>
		<IncludeTestAssembly>true</IncludeTestAssembly>
		<!--centralising TestResults output could reduce abitity to run tests in parralel-->
		<CoverletOutput>$(MSBuildThisFileDirectory)TestResults/</CoverletOutput>
		<MergeWith>$(MSBuildThisFileDirectory)TestResults/coverage.json</MergeWith>

	</PropertyGroup>
</Project>
