<Project Sdk="Microsoft.NET.Sdk.Razor">
	<ItemGroup>
		<!--Use solutions read me as package readme-->
		<None Include="..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<EnableDefaultEmbeddedResources>true</EnableDefaultEmbeddedResources>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>

		<GeneratePackageOnBuild Condition="'$(DisablePackageGeneration)' != 'true'">true</GeneratePackageOnBuild>
		<PackageId>TELBlazor.Components</PackageId>
		<Version>$(TELBlazorPackageVersion)</Version>
		<Authors>TEL</Authors>
		<Company>NHS</Company>
		<Description>WCAG Progressive Enhancement Blazor Component Library</Description>
		<PackageTags>NHS, TEL, Blazor, components, library, WCAG</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<RepositoryUrl>https://github.com/TechnologyEnhancedLearning/TELBlazor</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageOutputPath>$(NupkgOutputPath)</PackageOutputPath>
		<Configurations>Debug;Release</Configurations>

	</PropertyGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" />
		<PackageReference Include="Microsoft.Extensions.Http" />
		<!--OptionalImplementations add package weight in future it may be beneficial to make them a seperate package-->
		<PackageReference Include="Blazored.LocalStorage" />
		<PackageReference Include="Serilog" />
	</ItemGroup>
	<ItemGroup>
		<Content Remove="packages.lock.json" />
		<Content Remove="wwwroot\background.png" />
	</ItemGroup>
	<!--So cicd can test against a package in its container rather than a reference which isnt as close to the final product as the package-->
	<ItemGroup>
		<Compile Remove="..\CICDPackageLocation\**\*.cs" />
		<Content Remove="..\CICDPackageLocation\**\*" />
		<None Remove="..\CICDPackageLocation\**\*" />
	</ItemGroup>

	<!--<ItemGroup>
	  <Content Include="Core\DI\gitinclude.txt" />
	</ItemGroup>-->
	<ItemGroup>
		<Folder Include="Assets\" />
		<Folder Include="OptionalImplementations\Test\TestServices\" />
		<Folder Include="wwwroot\css\" />
		<Folder Include="wwwroot\js\" />
	</ItemGroup>
	<ItemGroup>
		<Content Update="wwwroot\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<Target Name="RunGulp" BeforeTargets="PrepareForBuild">
		 <!-- 
			1) Use solution root as working dir so npx picks up root/node_modules
			2) Tell gulp to run the gulpfile in this project directory
			3) Gulp to add the TELFrontend css version to version info file
		  -->
		<Exec WorkingDirectory="$(MSBuildProjectDirectory)/.." Command="npx gulp --cwd &quot;$(MSBuildProjectDirectory)&quot; --gulpfile &quot;$(MSBuildProjectDirectory)/gulpfile.js&quot;" />
	</Target>

</Project>

