<Project Sdk="Microsoft.NET.Sdk.Razor">
	<ItemGroup>
		<!--Use solutions read me as package readme-->
		<None Include="..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<EnableDefaultEmbeddedResources>true</EnableDefaultEmbeddedResources>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>

		<GeneratePackageOnBuild Condition="'$(DisablePackageGeneration)' != 'true'">true</GeneratePackageOnBuild>
		<PackageId>TELBlazor.Components</PackageId>
		<Version>$(TELBlazorPackageVersion)</Version>
		<Authors>TEL</Authors>
		<Company>NHS</Company>
		<Description>WCAG Progressive Enhancement Blazor Component Library</Description>
		<PackageTags>NHS, TEL, Blazor, components, library, WCAG</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<RepositoryUrl>https://github.com/TechnologyEnhancedLearning/TELBlazor</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageOutputPath>$(NugetPackagesOutputPath)</PackageOutputPath>
		<Configurations>Debug;Release</Configurations>

	</PropertyGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" />
		<PackageReference Include="Microsoft.Extensions.Http" />
		<!--OptionalImplementations add package weight in future it may be beneficial to make them a seperate package-->
		<PackageReference Include="Blazored.LocalStorage" />
		<PackageReference Include="Serilog" />
	</ItemGroup>
	<ItemGroup>
		<Content Remove="packages.lock.json" />
		<Content Remove="wwwroot\background.png" />
	</ItemGroup>
	<!--So cicd can test against a package in its container rather than a reference which isnt as close to the final product as the package-->
	<ItemGroup>
		<Compile Remove="..\CICDPackageLocation\**\*.cs" />
		<Content Remove="..\CICDPackageLocation\**\*" />
		<None Remove="..\CICDPackageLocation\**\*" />
	</ItemGroup>
	<ItemGroup>
		<Folder Include="Assets\" />
		<Folder Include="OptionalImplementations\Test\TestServices\" />
		<Folder Include="wwwroot\css\" />
		<Folder Include="wwwroot\js\" />
	</ItemGroup>
	<ItemGroup>
		<Content Update="wwwroot\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<!--
		Build partial classes for the version info. Compile version into before rest of the project so accessible for razor.
	-->
	<PropertyGroup>
		<!-- Exclude generated files from auto-inclusion to prevent duplicates as we want to control order of compilation-->
		<DefaultItemExcludes>$(DefaultItemExcludes);TELBlazorPackageVersion\VersionInfo.*.cs</DefaultItemExcludes>
	</PropertyGroup>
	<Target Name="PreBuildCleanup" BeforeTargets="GenerateTELBlazorPackageVersion;RunGulp;CoreCompile;BeforeCompile">
		<Delete Files="TELBlazorPackageVersion/VersionInfo.TELBlazor.cs" />
	</Target>
	<Target Name="GenerateTELBlazorPackageVersion" DependsOnTargets="PreBuildCleanup" BeforeTargets="RunGulp;CoreCompile;BeforeCompile">
		<WriteLinesToFile
			File="TELBlazorPackageVersion\VersionInfo.TELBlazor.cs"
			Lines="// This file is auto-generated. Do not edit manually.
namespace TELBlazor.Components.TELBlazorPackageVersion
{
	public static partial class VersionInfo
	{
		public const string TELBlazorPackageVersion = &quot;$(TELBlazorPackageVersion)&quot;%3B;
	}
}"
			Overwrite="true"
			Encoding="UTF-8" />
	</Target>
	<Target Name="RunGulp" DependsOnTargets="GenerateTELBlazorPackageVersion" BeforeTargets="CoreCompile;BeforeCompile">
		<Exec WorkingDirectory="$(MSBuildProjectDirectory)/.."
			  Command="npx gulp --cwd &quot;$(MSBuildProjectDirectory)&quot; --gulpfile &quot;$(MSBuildProjectDirectory)/gulpfile.js&quot;" />
	</Target>
	<Target Name="CompileVersionInfoBeforeRazor" DependsOnTargets="GenerateTELBlazorPackageVersion;RunGulp;PreBuildCleanup" BeforeTargets="CoreCompile;BeforeCompile">
		<ItemGroup>
			<Compile Include="TELBlazorPackageVersion\VersionInfo.TELBlazor.cs" />
			<Compile Include="TELBlazorPackageVersion\VersionInfo.TELFrontEnd.cs" />
		</ItemGroup>
	</Target>
</Project>

