# qqqq to do


name: Pull Request Checks

on:
  pull_request:
    branches: ['**']  # Run on all branches

jobs:
  call-reusable-ci-checks-workflow:
    name: Run CI Checks
    uses: ./.github/workflows/reuseable-ci-checks.yml
    with:
      runall: true