# qqqq to do

name: Pull Request Checks

on:
  pull_request:
    branches: ['**']  # Run on all branches

jobs:
  pull-request-call-reusable-ci-checks-workflow:
    name: Pull Request run CI Checks
    uses: ./.github/workflows/reuseable-ci-checks.yml
    with:
      runall: true